"""create sub_tiers table

Revision ID: 8b35075feed8
Revises: e8a4983421dd
Create Date: 2024-12-14 11:35:31.285743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b35075feed8'
down_revision: Union[str, None] = 'e8a4983421dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sub_tiers',
        sa.Column('title', sa.String(length=50), nullable=False),
        sa.Column('body', sa.String(length=500), nullable=False),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('subscription_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'title', name='unique_title_user_id')
    )
    op.add_column(
        'posts', sa.Column('sub_tier_id', sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, 'posts', 'sub_tiers', ['sub_tier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'sub_tier_id')
    op.drop_table('sub_tiers')
    # ### end Alembic commands ###
